### ISSUE TITLE
Getting error when ran the example files.

### ISSUE THREAD

**Issue by sam1064max** [bbitmaster/ale_python_interface#4]
./ale_python_test2.py space_invaders.bin
A.L.E: Arcade Learning Environment (version 0.5.1)
[Powered by Stella]
Use -help for help screen.
Warning: couldn't load settings file: ./ale.cfg
Traceback (most recent call last):
  File "./ale_python_test2.py", line 19, in <module>
    ale.set("random_seed",123)
AttributeError: 'ALEInterface' object has no attribute 'set'

**Comment by payal211** [comment]
1. - A.L.E: Arcade Learning Environment (version 0.6.0)
2. - [Powered by Stella]
3. - Use -help for help screen.
4. - Warning: couldn't load settings file: ./ale.cfg
5. - Traceback (most recent call last):
6. - File "./ale_python_test1.py", line 20, in <module>
7. - ale.set("random_seed",123)
8. - AttributeError: 'ALEInterface' object has no attribute 'set'


I am getting the same error. Any solution?
Thanks.
